name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello World!"
      - name: Machine Details
        run: echo uname -a
      - name: Goodbye
        run: echo "Done - goodbye!"
